### ISSUE TITLE
TLS seemingly broken with Trio backend 

### ISSUE THREAD

**Issue by Fuyukai** [agronholm/anyio#10]
```
Traceback (most recent call last):
  File "/home/laura/.virtualenvs/asyncws-Sz4NY5bC/lib/python3.6/site-packages/anyio/_networking.py", line 150, in start_tls
    self._raw_socket.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:841)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laura/dev/libs/asyncws/aa.py", line 17, in <module>
    anyio.run(test, backend="trio")
  File "/home/laura/.virtualenvs/asyncws-Sz4NY5bC/lib/python3.6/site-packages/anyio/__init__.py", line 112, in run
    return asynclib.run(func, *args, **backend_options)
  File "/home/laura/.virtualenvs/asyncws-Sz4NY5bC/lib/python3.6/site-packages/trio/_core/_run.py", line 1397, in run
    return result.unwrap()
  File "/home/laura/.virtualenvs/asyncws-Sz4NY5bC/lib/python3.6/site-packages/trio/_core/_result.py", line 119, in unwrap
    raise self.error
  File "/home/laura/.virtualenvs/asyncws-Sz4NY5bC/lib/python3.6/site-packages/trio/_core/_run.py", line 1502, in run_impl
    msg = task.coro.send(next_send)
  File "/home/laura/.virtualenvs/asyncws-Sz4NY5bC/lib/python3.6/site-packages/trio/_core/_run.py", line 1085, in init
    return system_nursery._reap_and_unwrap(task)
  File "/home/laura/.virtualenvs/asyncws-Sz4NY5bC/lib/python3.6/site-packages/trio/_core/_run.py", line 447, in _reap_and_unwrap
    return task._result.unwrap()
  File "/home/laura/.virtualenvs/asyncws-Sz4NY5bC/lib/python3.6/site-packages/trio/_core/_result.py", line 119, in unwrap
    raise self.error
  File "/home/laura/.virtualenvs/asyncws-Sz4NY5bC/lib/python3.6/site-packages/trio/_core/_run.py", line 1502, in run_impl
    msg = task.coro.send(next_send)
  File "/home/laura/dev/libs/asyncws/aa.py", line 10, in test
    async with open_websocket("wss://echo.websocket.org") as ws:
  File "/home/laura/.virtualenvs/asyncws-Sz4NY5bC/lib/python3.6/site-packages/async_generator/_util.py", line 34, in __aenter__
    return await self._agen.asend(None)
  File "/home/laura/dev/libs/asyncws/asyncwebsockets/client.py", line 25, in open_websocket
    await ws.__ainit__(addr=addr, ssl=ssl, path=url.path)
  File "/home/laura/dev/libs/asyncws/asyncwebsockets/_specific/anyio.py", line 15, in __ainit__
    self._sock = await anyio.connect_tcp(*addr, tls=True)
  File "/home/laura/.virtualenvs/asyncws-Sz4NY5bC/lib/python3.6/site-packages/anyio/__init__.py", line 301, in connect_tcp
    await stream.start_tls()
  File "/home/laura/.virtualenvs/asyncws-Sz4NY5bC/lib/python3.6/site-packages/anyio/_networking.py", line 216, in start_tls
    await self._socket.start_tls(ssl_context, self._server_hostname)
  File "/home/laura/.virtualenvs/asyncws-Sz4NY5bC/lib/python3.6/site-packages/anyio/_networking.py", line 153, in start_tls
    await self._wait_readable()
  File "/home/laura/.virtualenvs/asyncws-Sz4NY5bC/lib/python3.6/site-packages/trio/_core/__init__.py", line 47, in wait_socket_readable
    raise TypeError("need a socket")
TypeError: need a socket
```

**Comment by agronholm** [comment]
There is a test to verify that TLS works. If you have another use case I could add to the tests, then please elaborate.

**Comment by Fuyukai** [comment]
```py
import anyio


async def main():
    conn = await anyio.connect_tcp("echo.websocket.org", 443, tls=True)

anyio.run(main, backend="trio")
```

This is a repro, and doesn't work.

**Comment by Fuyukai** [comment]
Closed, user error.
