### ISSUE TITLE
[Trio] Task groups are marked inactive early

### ISSUE THREAD

**Issue by Fuyukai** [agronholm/anyio#11]
Code:
```py
import anyio


async def second():
    print("This never happens")


async def first(tg):
    await anyio.sleep(0)
    await tg.spawn(second)


async def main():
    async with anyio.create_task_group() as tg:
        await tg.spawn(first, tg)


anyio.run(main, backend="trio")
```

Error:
```py
Traceback (most recent call last):
  File "/home/laura/dev/discord/curious/aaa.py", line 18, in <module>
    anyio.run(main, backend="trio")
  File "/home/laura/.local/share/virtualenvs/curious-yiBjxk2Q/lib/python3.7/site-packages/anyio/__init__.py", line 112, in run
    return asynclib.run(func, *args, **backend_options)
  File "/home/laura/.local/share/virtualenvs/curious-yiBjxk2Q/lib/python3.7/site-packages/trio/_core/_run.py", line 1337, in run
    raise runner.main_task_outcome.error
  File "/home/laura/dev/discord/curious/aaa.py", line 15, in main
    await tg.spawn(first, tg)
  File "/home/laura/.local/share/virtualenvs/curious-yiBjxk2Q/lib/python3.7/site-packages/async_generator/_util.py", line 42, in __aexit__
    await self._agen.asend(None)
  File "/home/laura/.local/share/virtualenvs/curious-yiBjxk2Q/lib/python3.7/site-packages/async_generator/_impl.py", line 366, in step
    return await ANextIter(self._it, start_fn, *args)
  File "/home/laura/.local/share/virtualenvs/curious-yiBjxk2Q/lib/python3.7/site-packages/async_generator/_impl.py", line 202, in send
    return self._invoke(self._it.send, value)
  File "/home/laura/.local/share/virtualenvs/curious-yiBjxk2Q/lib/python3.7/site-packages/async_generator/_impl.py", line 209, in _invoke
    result = fn(*args)
  File "/home/laura/.local/share/virtualenvs/curious-yiBjxk2Q/lib/python3.7/site-packages/anyio/_backends/trio.py", line 90, in create_task_group
    tg._active = False
  File "/home/laura/.local/share/virtualenvs/curious-yiBjxk2Q/lib/python3.7/site-packages/trio/_core/_run.py", line 397, in __aexit__
    raise combined_error_from_nursery
  File "/home/laura/dev/discord/curious/aaa.py", line 10, in first
    await tg.spawn(second)
  File "/home/laura/.local/share/virtualenvs/curious-yiBjxk2Q/lib/python3.7/site-packages/anyio/_backends/trio.py", line 78, in spawn
    raise RuntimeError('This task group is not active; no new tasks can be spawned.')
RuntimeError: This task group is not active; no new tasks can be spawned.
```

Both curio and asyncio backends allow this to work.

**Comment by agronholm** [comment]
Just goes to show how difficult it is to create a comprehensive test suite.
