### ISSUE TITLE
conftest.py anyio backend specification doesn't

### ISSUE THREAD

**Issue by smurfix** [agronholm/anyio#159]
```
$ cat tests/conftest.py 
import pytest

@pytest.fixture
def anyio_backend():
    return 'trio'

$ pytest -sxv tests/
…
Traceback (most recent call last):
  File "/src/anyio/src/anyio/_backends/_asyncio.py", line 761, in send
    self._transport.write(item)
  File "uvloop/handles/stream.pyx", line 673, in uvloop.loop.UVStream.write
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x163bb70>; the handler is closed
```

**Comment by smurfix** [comment]
There's also no longer a command-line flag for backend selection when using pytest, which I'd like to have back if possible.

**Comment by agronholm** [comment]
> There's also no longer a command-line flag for backend selection when using pytest, which I'd like to have back if possible.

This is mentioned in the changelog, along with an alternative. The command line option could not work together with the `anyio_backend` fixture.

I will look into the problem with custom `anyio_backend` fixture.

**Comment by smurfix** [comment]
Umm, isn't there a way to register your own pytest option, which you could then use to control which string the fixture returns?

**Comment by agronholm** [comment]
The first half of that is true, the latter is not – at least I could not figure out how.

**Comment by agronholm** [comment]
It's trivial to do `-k "not trio and not curio"` though.

**Comment by smurfix** [comment]
Possibly. The problem is that `-k "not asyncio"` emits the same error, i.e. it has no effect, at least not on my system.
`-k trio` however works.

**Comment by agronholm** [comment]
That's only because for some reason it's not picking up your fixture.

**Comment by agronholm** [comment]
Can you show me the full output of the pytest run with `-v`?

**Comment by smurfix** [comment]
NB, I verified via `strace` that my `conftest.py` was in fact opened.

```
========================================== test session starts ==========================================
platform linux -- Python 3.8.5, pytest-4.6.9.2.10, py-1.7.0, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/src/distmqtt/.hypothesis/examples')
rootdir: /src/distmqtt
plugins: anyio-2.0.0.post81+dirty, pep8-1.0.6, trio-0.5.2, hypothesis-5.29.0, requests-mock-1.5.2, pylint-0.15.1, doctest-custom-1.1.0.dev0, cov-2.8.1, asyncio-0.10.0
collected 98 items                                                                                      
tests/test_broker.py::BrokerTest::test_client_connect PASSED                                      [  1%]
tests/test_broker.py::BrokerTest::test_client_connect_clean_session_false FAILED                  [  2%]

=============================================== FAILURES ================================================
__________________________ BrokerTest.test_client_connect_clean_session_false ___________________________

self = <tests.test_broker.BrokerTest testMethod=test_client_connect_clean_session_false>
MockPluginManager = <AsyncMock name='PluginManager' id='139653381639808'>

    @patch("distmqtt.broker.PluginManager", new_callable=AsyncMock)
    def test_client_connect_clean_session_false(
        self, MockPluginManager
    ):  # pylint: disable=unused-argument
        async def test_coro():
            async with create_broker(
                test_config, plugin_namespace="distmqtt.test.plugins"
            ) as broker:
                broker.plugins_manager._tg = broker._tg
                self.assertTrue(broker.transitions.is_started())
                async with open_mqttclient(
                    client_id="", config={"auto_reconnect": False}
                ) as client:
                    return_code = None
                    try:
                        await client.connect(URL, cleansession=False)
                    except ConnectException as ce:
                        return_code = ce.return_code
                    self.assertEqual(return_code, 0x02)
                    self.assertNotIn(client.session.client_id, broker._sessions)
    
>       anyio.run(test_coro)

tests/test_broker.py:176: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../anyio/src/anyio/_core/_eventloop.py:52: in run
    return asynclib.run(func, *args, **backend_options)  # type: ignore
../anyio/src/anyio/_backends/_asyncio.py:160: in run
    return native_run(wrapper(), debug=debug)
/usr/lib/python3.8/asyncio/runners.py:43: in run
    return loop.run_until_complete(main)
uvloop/loop.pyx:1456: in uvloop.loop.Loop.run_until_complete
    ???
../anyio/src/anyio/_backends/_asyncio.py:155: in wrapper
    return await func(*args)
tests/test_broker.py:160: in test_coro
    async with create_broker(
/usr/lib/python3.8/contextlib.py:171: in __aenter__
    return await self.gen.__anext__()
distmqtt/broker.py:171: in create_broker
    await tg.cancel_scope.cancel()
../anyio/src/anyio/_backends/_asyncio.py:434: in __aexit__
    raise exceptions[0]
../anyio/src/anyio/_backends/_asyncio.py:462: in _run_wrapped_task
    await func(*args)
distmqtt/broker.py:348: in server_task
    sock = await anyio.create_tcp_listener(local_port=port, local_host=address)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    async def create_tcp_listener(
        *, local_host: Optional[IPAddressType] = None, local_port: int = 0,
        family: AnyIPAddressFamily = socket.AddressFamily.AF_UNSPEC, backlog: int = 65536,
        reuse_port: bool = False
    ) -> MultiListener[SocketStream[IPSockAddrType]]:
[…]

                # If only IPv6 was requested, disable dual stack operation
                if fam == socket.AF_INET6:
                    raw_socket.setsockopt(IPPROTO_IPV6, socket.IPV6_V6ONLY, 1)
    
>               raw_socket.bind(sockaddr)
E               OSError: [Errno 98] Address already in use

../anyio/src/anyio/_core/_sockets.py:257: OSError

```

**Comment by agronholm** [comment]
You're not even using the fixture, so why do you expect the code to be run on trio? The documentation of `anyio.run()` does say that it defaults to asyncio.

**Comment by agronholm** [comment]
`test_client_connect_clean_session_false()` should be an async test function, don't you agree?

**Comment by agronholm** [comment]
The command line switch would not have made a difference here either.

**Comment by smurfix** [comment]
Ugh. I'm stupid. Sorry about that.
