### ISSUE TITLE
Exception in aclose of MultiListener

### ISSUE THREAD

**Issue by space88man** [agronholm/anyio#174]
anyio == 2.0.2

I am getting weird Exceptions when trying to gracefully stop a MultiListener with `aclose()`

```python
from  anyio import create_task_group, create_tcp_listener, sleep, run

async def handler(client):
    print("client connected")

async def main():

    listener = await create_tcp_listener(local_port=12345)
    async with create_task_group() as tg:
        await tg.spawn(listener.serve, handler)

        await sleep(5.0)

        print("Leaving task block")
        await listener.aclose()
        await tg.cancel_scope.cancel()


run(main)
```

Output:
```
Leaving task block
Traceback (most recent call last):
  File "/work/vagrant/Voice/trioswitch/test_1.py", line 21, in <module>
    run(main)
  File "/work/vagrant/Python/venv39/lib64/python3.9/site-packages/anyio/_core/_eventloop.py", line 52, in run
    return asynclib.run(func, *args, **backend_options)  # type: ignore
  File "/work/vagrant/Python/venv39/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 160, in run
    return native_run(wrapper(), debug=debug)
  File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/work/vagrant/Python/venv39/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 155, in wrapper
    return await func(*args)
  File "/work/vagrant/Voice/trioswitch/test_1.py", line 18, in main
    await tg.cancel_scope.cancel()
  File "/work/vagrant/Python/venv39/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 438, in __aexit__
    raise exceptions[0]
  File "/work/vagrant/Python/venv39/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 466, in _run_wrapped_task
    await func(*args)
  File "/work/vagrant/Python/venv39/lib64/python3.9/site-packages/anyio/streams/stapled.py", line 113, in serve
    await tg.spawn(listener.serve, handler, task_group)
  File "/work/vagrant/Python/venv39/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 436, in __aexit__
    raise ExceptionGroup(exceptions)
anyio._backends._asyncio.ExceptionGroup: 2 exceptions were raised in the task group:
----------------------------
Traceback (most recent call last):

  File "/work/vagrant/Python/venv39/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 809, in accept
    client_sock, _addr = await self._loop.sock_accept(self._raw_socket)

  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 561, in sock_accept
    return await fut

asyncio.exceptions.CancelledError


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/work/vagrant/Python/venv39/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 466, in _run_wrapped_task
    await func(*args)

  File "/work/vagrant/Python/venv39/lib64/python3.9/site-packages/anyio/abc/sockets.py", line 108, in serve
    stream = await self.accept()

  File "/work/vagrant/Python/venv39/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 813, in accept
    self._loop.remove_reader(self._raw_socket)

  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 341, in remove_reader
    return self._remove_reader(fd)

  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 277, in _remove_reader
    key = self._selector.get_key(fd)

  File "/usr/lib64/python3.9/selectors.py", line 191, in get_key
    return mapping[fileobj]

  File "/usr/lib64/python3.9/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)

  File "/usr/lib64/python3.9/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)

  File "/usr/lib64/python3.9/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))

ValueError: Invalid file descriptor: -1
----------------------------
Traceback (most recent call last):

  File "/work/vagrant/Python/venv39/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 809, in accept
    client_sock, _addr = await self._loop.sock_accept(self._raw_socket)

  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 561, in sock_accept
    return await fut

asyncio.exceptions.CancelledError


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/work/vagrant/Python/venv39/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 466, in _run_wrapped_task
    await func(*args)

  File "/work/vagrant/Python/venv39/lib64/python3.9/site-packages/anyio/abc/sockets.py", line 108, in serve
    stream = await self.accept()

  File "/work/vagrant/Python/venv39/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 813, in accept
    self._loop.remove_reader(self._raw_socket)

  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 341, in remove_reader
    return self._remove_reader(fd)

  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 277, in _remove_reader
    key = self._selector.get_key(fd)

  File "/usr/lib64/python3.9/selectors.py", line 191, in get_key
    return mapping[fileobj]

  File "/usr/lib64/python3.9/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)

  File "/usr/lib64/python3.9/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)

  File "/usr/lib64/python3.9/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))

ValueError: Invalid file descriptor: -1
```

**Comment by space88man** [comment]
Even if  I force a single listener `aclose()` doesn't seem to shutdown gracefully:

```python
from  anyio import create_task_group, create_tcp_listener, sleep, run


async def handler(client):
    print("client connected")


async def main():

    listener = await create_tcp_listener(local_port=12345, local_host='127.0.0.1')
    async with create_task_group() as tg:
        await tg.spawn(listener.serve, handler)

        await sleep(5.0)

        print("Leaving task block")
        await listener.aclose()
        await tg.cancel_scope.cancel()


run(main)
```

Output:
```
Leaving task block
Traceback (most recent call last):
  File "/work/vagrant/Voice/trioswitch/test_1.py", line 21, in <module>
    run(main)
  File "/work/vagrant/Python/venv39/lib64/python3.9/site-packages/anyio/_core/_eventloop.py", line 52, in run
    return asynclib.run(func, *args, **backend_options)  # type: ignore
  File "/work/vagrant/Python/venv39/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 160, in run
    return native_run(wrapper(), debug=debug)
  File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/work/vagrant/Python/venv39/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 155, in wrapper
    return await func(*args)
  File "/work/vagrant/Voice/trioswitch/test_1.py", line 18, in main
    await tg.cancel_scope.cancel()
  File "/work/vagrant/Python/venv39/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 438, in __aexit__
    raise exceptions[0]
  File "/work/vagrant/Python/venv39/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 466, in _run_wrapped_task
    await func(*args)
  File "/work/vagrant/Python/venv39/lib64/python3.9/site-packages/anyio/streams/stapled.py", line 113, in serve
    await tg.spawn(listener.serve, handler, task_group)
  File "/work/vagrant/Python/venv39/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 438, in __aexit__
    raise exceptions[0]
  File "/work/vagrant/Python/venv39/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 466, in _run_wrapped_task
    await func(*args)
  File "/work/vagrant/Python/venv39/lib64/python3.9/site-packages/anyio/abc/sockets.py", line 108, in serve
    stream = await self.accept()
  File "/work/vagrant/Python/venv39/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 813, in accept
    self._loop.remove_reader(self._raw_socket)
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 341, in remove_reader
    return self._remove_reader(fd)
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 277, in _remove_reader
    key = self._selector.get_key(fd)
  File "/usr/lib64/python3.9/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/lib64/python3.9/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/lib64/python3.9/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/lib64/python3.9/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
```

**Comment by agronholm** [comment]
Is there anything I need to do on the client side to reproduce the bug?
Does it manifest with backends other than asyncio?

**Comment by agronholm** [comment]
I see, no client is required.

**Comment by agronholm** [comment]
Looks like it only affects asyncio; the other backends raise a `ClosedResourceError` as they should.

If you want to close the listener properly, do it like this:
```python3
    listener = await create_tcp_listener(local_port=12345, local_host='127.0.0.1')
    async with listener, create_task_group() as tg:
        await tg.spawn(listener.serve, handler)

        await sleep(2.0)

        print("Leaving task block")
        await tg.cancel_scope.cancel()
```
