### ISSUE TITLE
TLSListener: exception during handshake

### ISSUE THREAD

**Issue by kinnay** [agronholm/anyio#177]
Run the [TLSListener example](https://anyio.readthedocs.io/en/stable/streams.html#using-self-signed-certificates), but comment out the line that calls `load_verify_locations`. Because the certificate is self-signed, the client will throw `ssl.SSLCertVerificationError`. However, the server also throws an exception:

```python
Traceback (most recent call last):
  File "/home/yannik/.local/lib/python3.8/site-packages/anyio/streams/tls.py", line 98, in _call_sslobject_method
    result = func(*args)
  File "/usr/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLSyscallError: Some I/O error occurred (_ssl.c:1108)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "server.py", line 25, in <module>
    run(main)
  File "/home/yannik/.local/lib/python3.8/site-packages/anyio/_core/_eventloop.py", line 52, in run
    return asynclib.run(func, *args, **backend_options)  # type: ignore
  File "/home/yannik/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 160, in run
    return native_run(wrapper(), debug=debug)
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "/home/yannik/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 155, in wrapper
    return await func(*args)
  File "server.py", line 23, in main
    await listener.serve(handle)
  File "/home/yannik/.local/lib/python3.8/site-packages/anyio/streams/tls.py", line 208, in serve
    await self.listener.serve(handler_wrapper, task_group)
  File "/home/yannik/.local/lib/python3.8/site-packages/anyio/streams/stapled.py", line 113, in serve
    await tg.spawn(listener.serve, handler, task_group)
  File "/home/yannik/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 438, in __aexit__
    raise exceptions[0]
  File "/home/yannik/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 466, in _run_wrapped_task
    await func(*args)
  File "/home/yannik/.local/lib/python3.8/site-packages/anyio/abc/sockets.py", line 109, in serve
    await task_group.spawn(handler, stream)
  File "/home/yannik/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 438, in __aexit__
    raise exceptions[0]
  File "/home/yannik/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 466, in _run_wrapped_task
    await func(*args)
  File "/home/yannik/.local/lib/python3.8/site-packages/anyio/streams/tls.py", line 204, in handler_wrapper
    wrapped_stream = await TLSStream.wrap(stream, ssl_context=self.ssl_context,
  File "/home/yannik/.local/lib/python3.8/site-packages/anyio/streams/tls.py", line 92, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "/home/yannik/.local/lib/python3.8/site-packages/anyio/streams/tls.py", line 117, in _call_sslobject_method
    raise BrokenResourceError from exc
anyio.BrokenResourceError
```

There seems to be no way to catch this exception before it crashes the server. I can put a `try-except` around `await listener.serve(handle)` and restart the server after the exception occurs, but at this point all clients have been disconnected already.

**Comment by agronholm** [comment]
Yeah, this is a problem that needs to be resolved. I'm not sure what the proper approach is – should we just log the errors?

**Comment by njsmith** [comment]
@agronholm this is one of the reasons why trio doesn't do the TLS handshake until after handing over to user code -- the handshake can fail, it can hang (so users need the option to control timeouts), etc.

**Comment by agronholm** [comment]
I've created a draft PR that fixes this problem. It will allow the continued usage of the Listener paradigm that maintains the separation of concerns between the listener chain and the actual serving code. Let me know if this suits you.

**Comment by agronholm** [comment]
I've made some changes to the PR, hopefully for the better.

**Comment by agronholm** [comment]
@kinnay you haven't commented yet. Have you looked at the PR?

**Comment by kinnay** [comment]
Yes, sorry, looks good to me.
