### ISSUE TITLE
curio backend spews extra error on main function erroring

### ISSUE THREAD

**Issue by Fuyukai** [agronholm/anyio#18]
```py
Traceback (most recent call last):
  File "/home/laura/.local/share/virtualenvs/curious-yiBjxk2Q/lib/python3.7/site-packages/anyio/_backends/curio.py", line 21, in run
    return kernel.run(func, *args)
  File "/home/laura/.local/share/virtualenvs/curious-yiBjxk2Q/lib/python3.7/site-packages/curio/kernel.py", line 180, in run
    raise ret_exc
  File "/home/laura/.local/share/virtualenvs/curious-yiBjxk2Q/lib/python3.7/site-packages/curio/kernel.py", line 746, in _run_coro
    trap = current._send(current.next_value)
  File "/home/laura/.local/share/virtualenvs/curious-yiBjxk2Q/lib/python3.7/site-packages/curio/task.py", line 173, in _task_runner
    self.next_value = await coro
  File "/home/laura/dev/discord/curious/repro.py", line 23, in main
    await err()
  File "/home/laura/dev/discord/curious/repro.py", line 19, in err
    raise AttributeError("fewsfwsefwf")
AttributeError: fewsfwsefwf

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laura/dev/discord/curious/repro.py", line 26, in <module>
    anyio.run(main, backend="curio")
  File "/home/laura/.local/share/virtualenvs/curious-yiBjxk2Q/lib/python3.7/site-packages/anyio/__init__.py", line 112, in run
    return asynclib.run(func, *args, **backend_options)
  File "/home/laura/.local/share/virtualenvs/curious-yiBjxk2Q/lib/python3.7/site-packages/anyio/_backends/curio.py", line 24, in run
    kernel.run(shutdown=True)
  File "/home/laura/.local/share/virtualenvs/curious-yiBjxk2Q/lib/python3.7/site-packages/curio/kernel.py", line 146, in run
    self._runner.send(None)
  File "/home/laura/.local/share/virtualenvs/curious-yiBjxk2Q/lib/python3.7/site-packages/curio/kernel.py", line 605, in _run_coro
    _init_loopback()
  File "/home/laura/.local/share/virtualenvs/curious-yiBjxk2Q/lib/python3.7/site-packages/curio/kernel.py", line 277, in _init_loopback
    kernel._call_at_shutdown(kernel._notify_sock.close)
  File "/home/laura/.local/share/virtualenvs/curious-yiBjxk2Q/lib/python3.7/site-packages/curio/kernel.py", line 133, in _call_at_shutdown
    self._shutdown_funcs.append(func)
AttributeError: 'NoneType' object has no attribute 'append'
```

Seems like you try and shut the kernel down when it's already done it internally.

**Comment by agronholm** [comment]
And if I don't do this, it breaks down even worse. I cannot help but to conclude that curio cannot, in its current state, be used correctly.
