### ISSUE TITLE
Incomplete traceback on Google App Engine

### ISSUE THREAD

**Issue by leshchenko1979** [agronholm/anyio#365]
I'm running a project on Google App Engine that uses `httpx` which in turn uses `anyio`.

The piece of code I'm running is (it's a bit abridged for simplicity):
```python
from httpcore import NetworkError, TimeoutException
from httpx import AsyncClient, HTTPError, Limits
from anyio import BrokenResourceError, ClosedResourceError
from json import JSONDecodeError

RETRIED_ERRORS = (
    TimeoutException,
    NetworkError,
    HTTPError,
    BrokenResourceError,
    ClosedResourceError,
    JSONDecodeError,
    RuntimeError,
    ConnectionError,
)

CONCURRENT_REQUEST_LIMIT = 10

def _create_client(self):
    self.client = AsyncClient(
        verify=False,
        limits=Limits(
            max_connections=CONCURRENT_REQUEST_LIMIT,
            max_keepalive_connections=CONCURRENT_REQUEST_LIMIT,
        ),
    )

async def post(self, url, json):
    for _ in range(MAX_ATTEMPTS):
        try:
            async with self.semaphore:
                if self.client.is_closed:
                    self._create_client()
                return await self.client.post(url, json=json, timeout=60)
        except RETRIED_ERRORS as err:
            pass

    raise RuntimeError from err

```
This code is run in parallel in 10 coroutines, but all in one thread (entrypoint in Google App Engine is set to `gunicorn -w 1`).

Two strange things happen:
1. I occasionally get a BrokenResourceError which somehow leaks through the `try / except` construct above.
2. When I get it, the logs show a trimmed traceback with no upper level sources mentioned:
```
Future exception was never retrieved
future: <Future finished exception=BrokenResourceError()>
Traceback (most recent call last):
  File "/opt/python3.9/lib/python3.9/asyncio/selector_events.py", line 856, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 60, in read
    return await self.stream.receive(n)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/anyio/streams/tls.py", line 152, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/anyio/streams/tls.py", line 109, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 1095, in receive
    raise self._protocol.exception
anyio.BrokenResourceError
```

**Comment by agronholm** [comment]
Could you try again with the master version? It could be related to https://github.com/agronholm/anyio/pull/364. Otherwise, I suggest you report this against httpx first and foremost since that is where you are seeing this problem. AnyIO raising this exception is not a bug per se.

**Comment by leshchenko1979** [comment]
Thanks @agronholm! I'm closing this one.
