### ISSUE TITLE
to_process.run_sync incompatible with httpx

### ISSUE THREAD

**Issue by Nifury** [agronholm/anyio#427]
I'm not sure if I should file this under `anyio` or `httpx`. 
In short, if we pass a function to `to_process.run_sync` where `httpx` is imported at the top-level, it throws an exception: 
```
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\lib\site-packages\anyio\to_process.py", line 136, in run_sync
    await send_raw_command(pickled)
  File "C:\Users\User\miniconda3\lib\site-packages\anyio\to_process.py", line 71, in send_raw_command
    raise retval
KeyError: '__main__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/User/PycharmProjects/deepbits/compositionanalysis/test.py", line 14, in <module>
    run(task)
  File "C:\Users\User\miniconda3\lib\site-packages\anyio\_core\_eventloop.py", line 56, in run
    return asynclib.run(func, *args, **backend_options)
  File "C:\Users\User\miniconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 233, in run
    return native_run(wrapper(), debug=debug)
  File "C:\Users\User\miniconda3\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\User\miniconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\User\miniconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 228, in wrapper
    return await func(*args)
  File "C:/Users/User/PycharmProjects/deepbits/compositionanalysis/test.py", line 10, in task
    await to_process.run_sync(test)
  File "C:\Users\User\miniconda3\lib\site-packages\anyio\to_process.py", line 141, in run_sync
    raise BrokenWorkerProcess('Error during worker process initialization') from exc
anyio.BrokenWorkerProcess: Error during worker process initialization
```

Code to reproduce this issue:
```python
import httpx
from anyio import to_process, run


def test():
    print('hello')


async def task():
    await to_process.run_sync(test)


if __name__ == '__main__':
    run(task)
```

**Comment by agronholm** [comment]
I ran that exact script against AnyIO 3.5.0 and it didn't crash. It didn't print anything either though, but I made it write into a file instead so I know it's being run.

**Comment by agronholm** [comment]
Does the httpx import have anything to do with the problem? Does it work as expected if you remove the import?

**Comment by Nifury** [comment]
Yes, removing the import solves this issue. 
AnyIO 3.5.0, httpx 0.22.0.
Let me see if I can create a docker image to reproduce this. Will report back.

**Comment by Nifury** [comment]
Okay it's because I also have `uvicorn[standard]` installed. 
It now becomes more puzzling. 
For some reason `spec.loader.exec_module(main)` throws an exception, but I cannot step into this statement.

**Comment by agronholm** [comment]
The mere presence of uvicorn in the environment should not make any difference.

**Comment by agronholm** [comment]
But, I installed it and started getting the same error!

**Comment by agronholm** [comment]
The crucial component is not uvicorn itself, but `click`. Its presence causes this error to occur.

**Comment by Nifury** [comment]
Seems it is because of utils.py in `click`. 
```python
def _detect_program_name(
    path: t.Optional[str] = None, _main: ModuleType = sys.modules["__main__"]
) -> str:
```

`sys.modules["__main__"]` raises that KeyError. 
Swapping these two lines can solve this issue, but I'm not sure if it will have any side effects. 
https://github.com/agronholm/anyio/blob/eac52932b41dc7333a012c32d11d0f3bb6b892fb/src/anyio/to_process.py#L203-L204

**Comment by Nifury** [comment]
Ah there is already a PR. 
https://github.com/pallets/click/pull/2215
