### ISSUE TITLE
Keyboard interrupt is not handled correctly in nested task groups on asyncio backend

### ISSUE THREAD

**Issue by alegonz** [agronholm/anyio#458]
Hi, and thank you for this great library.

As stated in the title, when the code below is running on the `asyncio` backend I see that `"starting loop"` is printed again after hitting Ctrl+C. I have to press Ctrl+C again to terminate it completely. I was expecting the script to terminate immediately and without printing `"starting loop"` again after hitting Ctrl+C once. When run on the `trio` backend, it works as expected.

If I replace the `task_group_2.start_soon(anyio.sleep_forever)` line with `await anyio.sleep_forever()` it works as expected, so I don't understand what is going on here. Am I doing something wrong?

### Code snippet

```python
#!/usr/bin/env python3
# anyio_nested.py script
# Run as: ./anyio_nested.py [anyio|trio]
import sys
import anyio

async def main():
    while True:
        print("starting loop")
        async with anyio.create_task_group() as task_group_1:
            task_group_1.start_soon(anyio.sleep_forever)
            async with anyio.create_task_group() as task_group_2:
                task_group_2.start_soon(anyio.sleep_forever)

if __name__ == "__main__":
    try:
        anyio.run(main, backend=sys.argv[1])
    except KeyboardInterrupt:
        print("Got Ctrl+C")
```

### Log
```
$ ./anyio_nested.py asyncio
starting loop
^Cstarting loop
^CGot Ctrl+C
```

### System info
```
anyio == 3.6.1
trio == 0.21.0
python version == 3.10.2
```

**Comment by alegonz** [comment]
I managed to avoid the second loop with a signal handler, following the advice in the docs. The dreaded "Task exception was never retrieved" appears this time though, so the termination is still not entirely clean

```python
#!/usr/bin/env python3
import signal
import sys

import anyio

async def signal_handler():
    with anyio.open_signal_receiver(signal.SIGINT) as signals:
        async for _ in signals:
            raise KeyboardInterrupt

async def main():
    while True:
        print("starting loop")
        async with anyio.create_task_group() as task_group_1:
            task_group_1.start_soon(signal_handler)
            task_group_1.start_soon(anyio.sleep_forever)
            async with anyio.create_task_group() as task_group_2:
                task_group_2.start_soon(anyio.sleep_forever)

if __name__ == "__main__":
    try:
        anyio.run(main, backend=sys.argv[1])
    except KeyboardInterrupt:
        print("Got Ctrl+C")

```

### Log
```
$ ./anyio_nested.py asyncio
starting loop
^CGot Ctrl+C
Task exception was never retrieved
future: <Task finished name='__main__.main' coro=<main() done, defined at /Users/foo.bar/anyio_tests/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py:278> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "/Users/foo.bar/anyio_tests/./anyio_nested.py", line 36, in <module>
    anyio.run(main, backend=sys.argv[1])
  File "/Users/foo.bar/anyio_tests/venv/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/Users/foo.bar/anyio_tests/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/Users/foo.bar/.pyenv/versions/3.10.2/lib/python3.10/asyncio/runners.py", line 47, in run
    _cancel_all_tasks(loop)
  File "/Users/foo.bar/.pyenv/versions/3.10.2/lib/python3.10/asyncio/runners.py", line 63, in _cancel_all_tasks
    loop.run_until_complete(tasks.gather(*to_cancel, return_exceptions=True))
  File "/Users/foo.bar/.pyenv/versions/3.10.2/lib/python3.10/asyncio/base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "/Users/foo.bar/.pyenv/versions/3.10.2/lib/python3.10/asyncio/base_events.py", line 595, in run_forever
    self._run_once()
  File "/Users/foo.bar/.pyenv/versions/3.10.2/lib/python3.10/asyncio/base_events.py", line 1881, in _run_once
    handle._run()
  File "/Users/foo.bar/.pyenv/versions/3.10.2/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/foo.bar/0_work/sandbox/anyio_tests/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/Users/foo.bar/0_work/sandbox/anyio_tests/./anyio_nested.py", line 27, in main
    async with anyio.create_task_group() as task_group_1:
  File "/Users/foo.bar/0_work/sandbox/anyio_tests/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/Users/foo.bar/.pyenv/versions/3.10.2/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/foo.bar/.pyenv/versions/3.10.2/lib/python3.10/asyncio/base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "/Users/foo.bar/.pyenv/versions/3.10.2/lib/python3.10/asyncio/base_events.py", line 595, in run_forever
    self._run_once()
  File "/Users/foo.bar/.pyenv/versions/3.10.2/lib/python3.10/asyncio/base_events.py", line 1881, in _run_once
    handle._run()
  File "/Users/foo.bar/.pyenv/versions/3.10.2/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/foo.bar/0_work/sandbox/anyio_tests/./anyio_nested.py", line 16, in signal_handler
    raise KeyboardInterrupt
KeyboardInterrupt
```

**Comment by alegonz** [comment]
Hmmm, I thought it was related to nested task groups but this simpler snippet also behaves similarly:
```python
#!/usr/bin/env python3
# anyio_nested.py script
# Run as: ./anyio_nested.py [anyio|trio]
import sys
import anyio

async def main():
    while True:
        print("starting loop")
        async with anyio.create_task_group() as task_group_1:
            task_group_1.start_soon(anyio.sleep_forever)

if __name__ == "__main__":
    try:
        anyio.run(main, backend=sys.argv[1])
    except KeyboardInterrupt:
        print("Got Ctrl+C")
```

**Comment by alegonz** [comment]
I guess this is the same issue as #148 .

**Comment by agronholm** [comment]
No, it's not. This relates to the difficulty of distinguishing between "native" task cancellations (which happen implicitly when you press ctrl+C) and cancellation by cancel scopes. The right duplicate reference is therefore #374.

**Comment by agronholm** [comment]
The problematic code is [here](https://github.com/agronholm/anyio/blob/master/src/anyio/_backends/_asyncio.py#L489-L490). The `CancelledError` is unconditionally swallowed there. I am in the process of refactoring the cancellation implementation to fix this, and leverage new functionality in Python 3.9+ to better tell apart native cancellations from `CancelScope` cancellations.

**Comment by alegonz** [comment]
@agronholm 
I see, thank you for the clarification! I'll close this issue since it is already covered by #374.
