### ISSUE TITLE
`BaseException` not returned though `blockingportal.start_task_soon(...).result()`

### ISSUE THREAD

**Issue by jonathanslenders** [agronholm/anyio#471]
Take this code:
```python
async def test() -> None:
    raise KeyboardInterrupt

    # Instead of the above raise statement, we can use prompt_toolkit to read
    # input. Pressing control-c raises a `KeyboardInterrupt` here. (That's not
    # the default SIGINT handler, which would be handled in the main thread.)
    from prompt_toolkit import PromptSession  # pip install prompt-toolkit

    await PromptSession().prompt_async(">")

    # Instead of `KeyboardInterrupt`, raising `BaseException` yields similar
    # results.
    raise BaseException("test")


def main() -> None:
    with start_blocking_portal() as portal:
        portal.start_task_soon(test).result()

        # We never get here:
        # - Either the code just hangs,
        # - the portal gets killed
        print("------")
        portal.start_task_soon(test).result()


if __name__ == "__main__":
    main()
```

The outcome of this is very nondeterministic.

Sometimes it hangs. Sometimes we get a short traceback. Sometimes a very long traceback. Usually the portal gets killed and becomes unusable.

What I'd expect is that any exception raised by our `test` function is returned through the `concurrent.futures.Future`, not killing the portal. A `KeyboardInterrupt` is a valid outcome of an async function and should not kill the portal.

What worries me most is that it's nondeterministic, and that it sometimes hangs, as if there is a race condition.

**Comment by smurfix** [comment]
Can you make the result deterministic by varying the PYTHONHASHSEED envvar?

**Comment by agronholm** [comment]
More than likely this is caused by asyncio's own flaky handling of `KeyboardInterrupt`.

**Comment by jonathanslenders** [comment]
@smurfix: Running as `PYTHONHASHSEED=0 python bug.py` doesn't help. It's still not deterministic.

@agronholm: I'm pretty sure it's also not asyncio's `KeyboardInterrupt` handling. The issue appears with any `BaseException`. (It was also not a `KeyboardInterrupt` thrown by the Python's default SIGINT handler).

**Comment by smurfix** [comment]
Huh. I get a consistent result with a `BaseException`, which admittedly can be improved somewhat:

```
EXCEPTION: BaseException('test')
Traceback (most recent call last):
  File "/src/anyio/src/anyio/from_thread.py", line 389, in run_portal
    await portal_.sleep_until_stopped()
  File "/src/anyio/src/anyio/from_thread.py", line 162, in sleep_until_stopped
    await self._stop_event.wait()
  File "/src/anyio/src/anyio/_backends/_asyncio.py", line 1419, in wait
    if await self._event.wait():
  File "/usr/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/src/anyio/src/anyio/from_thread.py", line 412, in start_blocking_portal
    yield portal
  File "/tmp/ag.py", line 24, in main
    portal.start_task_soon(test).result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/src/anyio/src/anyio/_backends/_asyncio.py", line 1739, in wrapper
    return await func(*args)
  File "/src/anyio/src/anyio/from_thread.py", line 386, in run_portal
    async with BlockingPortal() as portal_:
  File "/src/anyio/src/anyio/from_thread.py", line 150, in __aexit__
    return await self._task_group.__aexit__(exc_type, exc_val, exc_tb)
  File "/src/anyio/src/anyio/_backends/_asyncio.py", line 510, in __aexit__
    raise exc
  File "/src/anyio/src/anyio/from_thread.py", line 199, in _call_func
    retval = await retval
  File "/tmp/ag.py", line 6, in test
    raise BaseException("test")
BaseException: test

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/ag.py", line 37, in <module>
    main()
  File "/tmp/ag.py", line 22, in main
    with start_blocking_portal() as portal:
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/src/anyio/src/anyio/from_thread.py", line 414, in start_blocking_portal
    portal.call(portal.stop, True)
  File "/src/anyio/src/anyio/from_thread.py", line 263, in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
  File "/src/anyio/src/anyio/from_thread.py", line 303, in start_task_soon
    self._check_running()
  File "/src/anyio/src/anyio/from_thread.py", line 154, in _check_running
    raise RuntimeError("This portal is not running")
RuntimeError: This portal is not running

```

The `KeyboardInterrupt` case _is_ worse, as the above is followed by:
```
Task exception was never retrieved
future: <Task finished name='anyio.from_thread.start_blocking_portal.<locals>.run_portal' coro=<start_blocking_portal.<locals>.run_portal() done, defined at /src/anyio/src/anyio/_backends/_asyncio.py:1730> exception=KeyboardInterrupt()>
Traceback (most recent call last):
```
plus another copy of the complete traceback.

**Comment by smurfix** [comment]
NB, using the Trio backend leaves the `RuntimeError: This portal is not running` problem but "fixes" the others.

**Comment by jonathanslenders** [comment]
With `BaseException`, sometimes I get:

```python
Traceback (most recent call last):
  File "/home/jonathan/.pyenv/versions/3.9.13/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jonathan/.pyenv/versions/env/lib/python3.9/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/home/jonathan/.pyenv/versions/env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/home/jonathan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/jonathan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/jonathan/.pyenv/versions/env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/home/jonathan/.pyenv/versions/env/lib/python3.9/site-packages/anyio/from_thread.py", line 472, in run_portal
    await portal_.sleep_until_stopped()
  File "/home/jonathan/.pyenv/versions/env/lib/python3.9/site-packages/anyio/from_thread.py", line 170, in __aexit__
    return await self._task_group.__aexit__(exc_type, exc_val, exc_tb)
  File "/home/jonathan/.pyenv/versions/env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 689, in __aexit__
    raise exceptions[0]
  File "/home/jonathan/.pyenv/versions/env/lib/python3.9/site-packages/anyio/from_thread.py", line 495, in start_blocking_portal
    yield portal
  File "/tmp/bug.py", line 21, in main
    portal.start_task_soon(test).result()
  File "/home/jonathan/.pyenv/versions/3.9.13/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/home/jonathan/.pyenv/versions/3.9.13/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/jonathan/.pyenv/versions/env/lib/python3.9/site-packages/anyio/from_thread.py", line 219, in _call_func
    retval = await retval
  File "/tmp/bug.py", line 16, in test
    raise BaseException("test")
BaseException: test

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/bug.py", line 31, in <module>
    main()
  File "/tmp/bug.py", line 27, in main
    portal.start_task_soon(test).result()
  File "/home/jonathan/.pyenv/versions/3.9.13/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/jonathan/.pyenv/versions/env/lib/python3.9/site-packages/anyio/from_thread.py", line 497, in start_blocking_portal
    portal.call(portal.stop, True)
  File "/home/jonathan/.pyenv/versions/env/lib/python3.9/site-packages/anyio/from_thread.py", line 283, in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
  File "/home/jonathan/.pyenv/versions/env/lib/python3.9/site-packages/anyio/from_thread.py", line 369, in start_task_soon
    self._spawn_task_from_thread(func, args, {}, name, f)
  File "/home/jonathan/.pyenv/versions/env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 1016, in _spawn_task_from_thread
    run_sync_from_thread(
  File "/home/jonathan/.pyenv/versions/env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 988, in run_sync_from_thread
    return f.result()
  File "/home/jonathan/.pyenv/versions/3.9.13/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/home/jonathan/.pyenv/versions/3.9.13/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/jonathan/.pyenv/versions/env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 975, in wrapper
    f.set_result(func(*args))
  File "/home/jonathan/.pyenv/versions/env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 821, in start_soon
    self._spawn(func, args, name)
  File "/home/jonathan/.pyenv/versions/env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 779, in _spawn
    raise RuntimeError(
RuntimeError: This task group is not active; no new tasks can be started.
```

Sometimes I get (I think this is what I'd expect): 
```python
Traceback (most recent call last):
  File "/tmp/bug.py", line 31, in <module>
    main()
  File "/tmp/bug.py", line 21, in main
    portal.start_task_soon(test).result()
  File "/home/jonathan/.pyenv/versions/3.9.13/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/home/jonathan/.pyenv/versions/3.9.13/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/jonathan/.pyenv/versions/env/lib/python3.9/site-packages/anyio/from_thread.py", line 219, in _call_func
    retval = await retval
  File "/tmp/bug.py", line 16, in test
    raise BaseException("test")
BaseException: test
```

and exceptionally I hangs. Pressing control-c at than point results in the following stacktrace:

```python
Traceback (most recent call last):
  File "/home/jonathan/.pyenv/versions/3.9.13/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jonathan/.pyenv/versions/radkit/lib/python3.9/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/home/jonathan/.pyenv/versions/radkit/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/home/jonathan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/jonathan/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/jonathan/.pyenv/versions/radkit/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/home/jonathan/.pyenv/versions/radkit/lib/python3.9/site-packages/anyio/from_thread.py", line 472, in run_portal
    await portal_.sleep_until_stopped()
  File "/home/jonathan/.pyenv/versions/radkit/lib/python3.9/site-packages/anyio/from_thread.py", line 170, in __aexit__
    return await self._task_group.__aexit__(exc_type, exc_val, exc_tb)
  File "/home/jonathan/.pyenv/versions/radkit/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 689, in __aexit__
    raise exceptions[0]
  File "/home/jonathan/.pyenv/versions/radkit/lib/python3.9/site-packages/anyio/from_thread.py", line 495, in start_blocking_portal
    yield portal
  File "/tmp/bug.py", line 21, in main
    portal.start_task_soon(test).result()
  File "/home/jonathan/.pyenv/versions/3.9.13/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/home/jonathan/.pyenv/versions/3.9.13/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/jonathan/.pyenv/versions/radkit/lib/python3.9/site-packages/anyio/from_thread.py", line 219, in _call_func
    retval = await retval
  File "/tmp/bug.py", line 16, in test
    raise BaseException("test")
BaseException: test

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/bug.py", line 31, in <module>
    main()
  File "/tmp/bug.py", line 27, in main
    portal.start_task_soon(test).result()
  File "/home/jonathan/.pyenv/versions/3.9.13/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/jonathan/.pyenv/versions/radkit/lib/python3.9/site-packages/anyio/from_thread.py", line 497, in start_blocking_portal
    portal.call(portal.stop, True)
  File "/home/jonathan/.pyenv/versions/radkit/lib/python3.9/site-packages/anyio/from_thread.py", line 283, in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
  File "/home/jonathan/.pyenv/versions/radkit/lib/python3.9/site-packages/anyio/from_thread.py", line 369, in start_task_soon
    self._spawn_task_from_thread(func, args, {}, name, f)
  File "/home/jonathan/.pyenv/versions/radkit/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 1016, in _spawn_task_from_thread
    run_sync_from_thread(
  File "/home/jonathan/.pyenv/versions/radkit/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 988, in run_sync_from_thread
    return f.result()
  File "/home/jonathan/.pyenv/versions/3.9.13/lib/python3.9/concurrent/futures/_base.py", line 441, in result
    self._condition.wait(timeout)
  File "/home/jonathan/.pyenv/versions/3.9.13/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
KeyboardInterrupt
```

**Comment by agronholm** [comment]
One part of the problem is that, since a `BaseException` (other than `CancelledError`) causes a hard shutdown of the asyncio event loop, the `BlockingPortal` causes another error by trying to shut down the portal that has already been shut down.

**Comment by agronholm** [comment]
@jonathanslenders ok, so is the expectation that any `BaseException` being raised in a task, which would normally kill the event loop, would _not_ be allowed to propagate to the event loop?

**Comment by jonathanslenders** [comment]
Yes, I'd expect any exception to be propagated through the `concurrent.futures.Future` because that's the place where it can/should be handled.

However, I just did some experiments, and looking at the following snippet, with `asyncio.create_task()`, any `BaseException` that's not an `Exception` kills the event loop too (+ I think the exception gets propagated a second time through the future):

```python
import asyncio

async def test() -> None:
    raise Exception('test')

    # Raise `KeyboardInterrupt` instead here. Looks like that kills the event
    # loop.
    #raise KeyboardInterrupt

async def main() -> None:
    t = asyncio.create_task(test())  # Same for `asyncio.ensure_future`
    await asyncio.sleep(1)
    print('Got exception in future:', t.exception())

asyncio.run(main())
```

I'm not sure whether this is a bug in asyncio, or whether there's a good reason for the given behavior.

For my project, I have a wrapper that deals with this issue + does a few other things too. (This code could be confusing because it deals with both a `KeyboardInterrupt` "injected" in the main thread, as well as a `KeyboardInterrupt` raised by code running in the event loop.)

```python
from __future__ import annotations
from typing import Any, Callable, Coroutine, TypeVar, cast
from anyio.from_thread import BlockingPortal

__all__ = ["do_async"]

_T = TypeVar("_T")


def do_async(portal: BlockingPortal, func: Callable[[], Coroutine[Any, Any, _T]]) -> _T:
    """
    Schedule an async call in the blocking portal, and wait for it.

    Pressing control-c in the main thread, will cancel the scheduled async
    call.
    """

    result: _T | None = None
    exception: BaseException | None = None

    async def in_loop() -> None:
        nonlocal result, exception
        try:
            result = await func()
        except BaseException as e:
            # NOTE: We should not let any `BaseException` propagate in our
            #       portal, because that terminates the portal.
            #       `KeyboardInterrupt` is one example.
            exception = e

    future = portal.start_task_soon(in_loop)
    try:
        future.result()  # Wait for the result.
    except KeyboardInterrupt:
        # If we got a KeyboardInterrupt in the sync thread here, cancel the
        # underlying async call.
        future.cancel()
        raise

    if exception is not None:
        raise exception
    return cast(_T, result)  # If no exception, result should have been set.
```

**Comment by agronholm** [comment]
> I'm not sure whether this is a bug in asyncio, or whether there's a good reason for the given behavior.

IIRC this was deliberate. I should also mention that **any** uncaught exception in a trio event loop also kills the event loop. Generally speaking, letting exceptions fall off a task is bad.

**Comment by jonathanslenders** [comment]
Right. So, the only remaining thing here is the nondeterministic weirdness I noticed. (I don't mind having the workaround I have now, it's not a typical use case. And with the workaround it also becomes deterministic.)

**Comment by smurfix** [comment]
> Yes, I'd expect any exception to be propagated through the concurrent.futures.Future because that's the place where it can/should be handled.

I'd expect an `Exception` to be propagated into the Future, yes. But not a `BaseException`. The latter should always be re-`raise`d (except for catching cancellations obviously); if there's a Future to be signalled along the way, fine, but please feed a new `Exception`-derived object to it. Not the original.

**Comment by agronholm** [comment]
Yeah, so the reason why `BaseException` kills an asyncio event loop is so that `SystemExit` and `KeyboardInterrupt` would propagate from the event loop instead of just failing whatever callback happened to be running at the time. Otherwise it would be difficult to cause an asyncio app to exit.

**Comment by smurfix** [comment]
> an asyncio app should only exit when the main function that's passed to asyncio.run() returns

Well, their adoption of taskgroups is another step away from treating asyncio as a randomly interruptible and re-enter-able "mainloop" thing. So maybe we can convince them to clean that up too, eventually.

**Comment by agronholm** [comment]
I've created the above PR to get rid of the `RuntimeError` which is just a side effect. Reviews are welcome.
