### ISSUE TITLE
Closing a process's stdout when there's more data to be read results in internal asyncio error

### ISSUE THREAD

**Issue by jwodder** [agronholm/anyio#490]
When using anyio with asyncio (This works fine with trio), if a subprocess is started with piped stdout and the stdout is closed (either explicitly or via context manager) before all data is read, asyncio will crash with a horrible traceback.

MVCE:

```python
import sys
import anyio

CODE = """\
import sys
for _ in range(1000):
    sys.stdout.buffer.write(bytes(range(256)))
"""

async def amain():
    async with await anyio.open_process([sys.executable, "-c", CODE]) as p:
        print(repr(await p.stdout.receive()))
        await p.stdout.aclose()  # The error even happens if you comment out this line!

if __name__ == "__main__":
    anyio.run(amain)
```

<details>
<summary>Output (after skipping the <code>print</code>'s output)</summary>

```
handle: <Handle SubprocessStreamProtocol.pipe_data_received(1, b'\x00\x01\x0...c\xfd\xfe\xff')>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/subprocess.py", line 72, in pipe_data_received
    reader.feed_data(data)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/streams.py", line 456, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback SubprocessStreamProtocol.pipe_data_received(1, b'\x00\x01\x0...c\xfd\xfe\xff')
handle: <Handle SubprocessStreamProtocol.pipe_data_received(1, b'\x00\x01\x0...c\xfd\xfe\xff')>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/subprocess.py", line 72, in pipe_data_received
    reader.feed_data(data)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/streams.py", line 456, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback SubprocessStreamProtocol.pipe_data_received(1, b'\x00\x01\x0...c\xfd\xfe\xff')
handle: <Handle SubprocessStreamProtocol.pipe_data_received(1, b'\x00\x01\x0...c\xfd\xfe\xff')>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/subprocess.py", line 72, in pipe_data_received
    reader.feed_data(data)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/streams.py", line 456, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback SubprocessStreamProtocol.pipe_data_received(1, b'\x00\x01\x0...c\xfd\xfe\xff')
handle: <Handle SubprocessStreamProtocol.pipe_data_received(1, b'\x00\x01\x0...c\xfd\xfe\xff')>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/subprocess.py", line 72, in pipe_data_received
    reader.feed_data(data)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/streams.py", line 456, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback SubprocessStreamProtocol.pipe_data_received(1, b'\x00\x01\x0...c\xfd\xfe\xff')
handle: <Handle SubprocessStreamProtocol.pipe_data_received(1, b'\x00\x01\x0...c\xfd\xfe\xff')>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/subprocess.py", line 72, in pipe_data_received
    reader.feed_data(data)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/streams.py", line 456, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
```

</details>

This behavior has been observed in the following environments:

* macOS 11.6.8, Python 3.10.8, anyio 3.6.2
* Debian 11 (bullseye), Python 3.8.13, anyio 3.6.1

**Comment by dolamroth** [comment]
I have the same error with:
Windows 10, Python 3.9.2, anyio==4.2.0

**Comment by agronholm** [comment]
@dolamroth would you mind validating the fix PR (see above for the link)?
