### ISSUE TITLE
Can't use `anyio.to_process` without full import

### ISSUE THREAD

**Issue by uSpike** [agronholm/anyio#526]
This works:

```python
from anyio import to_process
...
```
but this doesn't
```python
import anyio
anyio.to_process
...
```
This is surprising since `anyio.to_thread` works fine.

```
Python 3.10.5 (main, Jul  8 2022, 21:22:35) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import anyio
>>> anyio
<module 'anyio' from '/root/.cache/pypoetry/virtualenvs/xtf-Q5MrvEgg-py3.10/lib/python3.10/site-packages/anyio/__init__.py'>
>>> anyio.to_process
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'anyio' has no attribute 'to_process'. Did you mean: 'run_process'?
>>> anyio.to_thread
<module 'anyio.to_thread' from '/root/.cache/pypoetry/virtualenvs/xtf-Q5MrvEgg-py3.10/lib/python3.10/site-packages/anyio/to_thread.py'>
```

**Comment by agronholm** [comment]
I believe this is because `anyio.to_thread` gets implicitly imported during the execution of `anyio/__init__.py`, but `anyio.to_process` doesn't. I'm not sure if this should've been reported as a bug though.

**Comment by uSpike** [comment]
That's fair, can I re-scope this as a feature request to explicitly expose `to_process` and `to_thread` in the `anyio` namespace?

**Comment by agronholm** [comment]
I don't think users should expect this. For example:

```pycon
>>> import importlib
>>> importlib.metadata
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'importlib' has no attribute 'metadata'
>>> import importlib.metadata
>>> 
```

**Comment by agronholm** [comment]
In addition, implicitly importing all submodules would have a detrimental effect on the memory footprint.

**Comment by uSpike** [comment]
OK that's fair, thanks for the discussion.
