### ISSUE TITLE
Cancellation issue with asyncio and curio

### ISSUE THREAD

**Issue by vxgmichel** [agronholm/anyio#54]
The following test fails with the latest master (5a2b4c9):

```python
import pytest
import anyio


@pytest.mark.anyio
async def test():
    with pytest.raises(TimeoutError):
        async with anyio.fail_after(1):
            async with anyio.create_task_group() as group:
                await group.spawn(anyio.sleep, 2)
                await anyio.sleep(2)
```
Output:
```console
± pytest -v --anyio-backends=asyncio,trio,curio
============================ test session starts =============================
platform linux -- Python 3.7.2, pytest-3.10.1, py-1.7.0, pluggy-0.8.1 --
plugins: trio-0.5.1, asyncio-0.10.0, anyio-1.0.0rc1.post5

test.py::test[asyncio] FAILED                        [ 33%]
test.py::test[trio] PASSED                           [ 66%]
test.py::test[curio] FAILED                          [100%]
```
The corresponding asyncio exception:
```pytest
E           anyio._backends.asyncio.AsyncioExceptionGroup: 2 exceptions were raised in the task group:
E           ----------------------------
E           Traceback (most recent call last):
E           
E             File "/home/vinmic/anyio/anyio/_backends/asyncio.py", line 384, in _run_wrapped_task
E               await func(*args)
E           
E             File "/home/vinmic/anyio/anyio/_backends/asyncio.py", line 157, in sleep
E               await asyncio.sleep(delay)
E           
E             File "/home/vinmic/miniconda/lib/python3.7/asyncio/tasks.py", line 568, in sleep
E               return await future
E           
E           concurrent.futures._base.CancelledError
E           ----------------------------
E           Traceback (most recent call last):
E           
E             File "/home/vinmic/anyio/test.py", line 12, in test
E               await anyio.sleep(2)
E           
E             File "/home/vinmic/anyio/anyio/_backends/asyncio.py", line 157, in sleep
E               await asyncio.sleep(delay)
E           
E             File "/home/vinmic/miniconda/lib/python3.7/asyncio/tasks.py", line 568, in sleep
E               return await future
E           
E           concurrent.futures._base.CancelledError

../anyio/anyio/_backends/asyncio.py:375: AsyncioExceptionGroup
```

**Comment by agronholm** [comment]
Oh dear. I really had hoped to have ironed out the remaining issues with cancellation. But thanks for the report – now I can incorporate a fix to the first final release.
