### ISSUE TITLE
RuntimeError: dictionary changed size during iteration during import of anyio

### ISSUE THREAD

**Issue by ebw44** [agronholm/anyio#545]
# Context
The exception doesn't occur all the time and I have not been able to reproduce the problem with unit tests.  
It has happened only when running my code in vscode debugger, but once it happens it seems to reoccur more.  
In a regular terminal with the same python conda environment I haven't been able to trigger the problem.  
After a restart of vscode, I'm not able to reproduce the problem. I forgot to try to close the vscode 'Python debug console', before I did the restart of vscode, so I don't know if the state of the console was involved.

## Version
anyio=3.6.1=pyhd8ed1ab_1
python=3.11.0=hcf16a7b_0_cpython

# Error
I'm getting a `RuntimeError: dictionary changed size during iteration` from the `for key, value in list(locals().items())` code at the end of anyio/__init__.py
The initial code that triggers the exception is a simple get request using httpx
```python
async with httpx.AsyncClient(timeout=5.0, transport=self.transport) as client:
      res = await client.get(url, headers=self._with_token())
```
with `self.transport = httpx.AsyncHTTPTransport(retries=3)` and `self._with_token()` just returning a dict with authorization token.

Here is the full trace
```
Traceback (most recent call last):
  File "C:\Users\username\Documents\devel\Other\automation\rules\msgraphService.py", line 36, in _get
    res = await client.get(url, headers=self._with_token())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\mambaforge\envs\msgraph\Lib\site-packages\httpx\_client.py", line 1757, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\mambaforge\envs\msgraph\Lib\site-packages\httpx\_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\mambaforge\envs\msgraph\Lib\site-packages\httpx\_client.py", line 1620, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\mambaforge\envs\msgraph\Lib\site-packages\httpx\_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\mambaforge\envs\msgraph\Lib\site-packages\httpx\_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\mambaforge\envs\msgraph\Lib\site-packages\httpx\_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\mambaforge\envs\msgraph\Lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\mambaforge\envs\msgraph\Lib\site-packages\httpcore\_async\connection_pool.py", line 218, in handle_async_request
    async with self._pool_lock:
  File "C:\Users\username\mambaforge\envs\msgraph\Lib\site-packages\httpcore\_synchronization.py", line 36, in __aenter__
    self.setup()
  File "C:\Users\username\mambaforge\envs\msgraph\Lib\site-packages\httpcore\_synchronization.py", line 30, in setup
    import anyio
  File "C:\Users\username\mambaforge\envs\msgraph\Lib\site-packages\anyio\__init__.py", line 165, in <module>
    for key, value in list(locals().items()):
                      ^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: dictionary changed size during iteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\username\mambaforge\envs\msgraph\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\mambaforge\envs\msgraph\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "c:\Users\username\.vscode\extensions\ms-python.python-2023.4.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\username\.vscode\extensions\ms-python.python-2023.4.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\username\.vscode\extensions\ms-python.python-2023.4.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\username\.vscode\extensions\ms-python.python-2023.4.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\username\.vscode\extensions\ms-python.python-2023.4.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\username\.vscode\extensions\ms-python.python-2023.4.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "notice_board.py", line 458, in <module>
    asyncio.run(main())
  File "C:\Users\username\mambaforge\envs\msgraph\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\username\mambaforge\envs\msgraph\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\mambaforge\envs\msgraph\Lib\asyncio\base_events.py", line 650, in run_until_complete
    await enquiryLogUpdater.update_enquiries(args.include_regexp, n_coroutines)
  File "notice_board.py", line 69, in update_enquiries
    async with self._checkout_config(f"regexp: {regexp}") as config:
  File "C:\Users\username\mambaforge\envs\msgraph\Lib\contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "notice_board.py", line 111, in _checkout_config
    async with self._re_folder.checkout_document(self.config_filename, message, self.fail_if_config_is_checkout) as config_doc:
  File "C:\Users\username\mambaforge\envs\msgraph\Lib\contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\Documents\devel\Other\automation\rules\sharepointService.py", line 281, in checkout_document
    doc = await self.get_document(path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\Documents\devel\Other\automation\rules\sharepointService.py", line 207, in get_document
    res = await self._get(url)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\Documents\devel\Other\automation\rules\msgraphService.py", line 35, in _get
    async with httpx.AsyncClient(timeout=self.timeout) as client:
  File "C:\Users\username\mambaforge\envs\msgraph\Lib\site-packages\httpx\_client.py", line 2003, in __aexit__
    await self._transport.__aexit__(exc_type, exc_value, traceback)
  File "C:\Users\username\mambaforge\envs\msgraph\Lib\site-packages\httpx\_transports\default.py", line 332, in __aexit__
    await self._pool.__aexit__(exc_type, exc_value, traceback)
  File "C:\Users\username\mambaforge\envs\msgraph\Lib\site-packages\httpcore\_async\connection_pool.py", line 318, in __aexit__
    await self.aclose()
  File "C:\Users\username\mambaforge\envs\msgraph\Lib\site-packages\httpcore\_async\connection_pool.py", line 303, in aclose
    async with self._pool_lock:
  File "C:\Users\username\mambaforge\envs\msgraph\Lib\site-packages\httpcore\_synchronization.py", line 41, in __aenter__
    await self._anyio_lock.acquire()
          ^^^^^^^^^^^^^^^^
AttributeError: 'AsyncLock' object has no attribute '_anyio_lock'
```

**Comment by ebw44** [comment]
The problem came back on the new vscode instance, and closing the 'Python debug console' didn't fix the problem.  
Replacing `asyncio.run(main())` by `anyio.run(main)` seems to fix the problem (for the moment). It made me realize I never intended to use anyio, and it looks like the problem comes from httpcore. So I'm closing this issue for the one in httpcore

**Comment by smurfix** [comment]
This should fix it.

``` patch
diff --git src/anyio/__init__.py src/anyio/__init__.py
index e987385..835b48f 100644
--- src/anyio/__init__.py
+++ src/anyio/__init__.py
@@ -133,8 +133,8 @@ from ._core._testing import (
 from ._core._typedattr import TypedAttributeProvider, TypedAttributeSet, typed_attribute
 
 # Re-export imports so they look like they live directly in this package
-key: str
-value: Any
+key: str = None
+value: Any = None
 for key, value in list(locals().items()):
     if getattr(value, "__module__", "").startswith("anyio."):
         value.__module__ = __name__
```

**Comment by smurfix** [comment]
sorry about the confusion. I need to wake up more. :-/

**Comment by T-256** [comment]
@ebw44 I think the problem could be solve on anyio side.
let me try on this.
